apply plugin: 'com.android.application'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
} else {
    println "[警告]：local.properties 文件不存在"
}

android {
    compileSdkVersion 35
    buildToolsVersion '35.0.0'
    namespace 'com.example.simpleapp'
    defaultConfig {
        applicationId "com.example.simpleapp"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    }

    signingConfigs {
        config {
            keyAlias localProperties.getProperty('SIGN_KEY_ALIAS')
            keyPassword localProperties.getProperty('SIGN_KEY_PASSWORD')
            storeFile file(localProperties.getProperty('SIGN_STORE_FILE_PATH', 'simpleapp.jks'))
            storePassword localProperties.getProperty('SIGN_STORE_PASSWORD')
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.config
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            signingConfig signingConfigs.config
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    aaptOptions {
        additionalParameters '--auto-add-overlay'
        ignoreAssetsPattern "!.svn:!.git:.*:!CVS:!thumbs.db:!picasa.ini:!*.scc:*~"
    }
}

dependencies {
    // 引入 libs 目录下的所有 aar 和 jar 文件
    implementation fileTree(dir: 'libs', include: ['*.aar', '*.jar'], exclude: [])

    // 核心依赖
    // implementation "androidx.appcompat:appcompat:1.1.0"
    implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"
    implementation "androidx.core:core:1.1.0"
    implementation "androidx.fragment:fragment:1.1.0"
    implementation "androidx.recyclerview:recyclerview:1.1.0"
    implementation "com.facebook.fresco:fresco:2.5.0"
    implementation "com.facebook.fresco:animated-gif:2.5.0"
    // implementation "com.github.bumptech.glide:glide:4.9.0"
    implementation "com.alibaba:fastjson:1.2.83"
    implementation "androidx.webkit:webkit:1.5.0"
    implementation "com.squareup.okhttp3:okhttp:3.12.12"
    implementation "net.lingala.zip4j:zip4j:2.11.5"

    // TUICallKit
    implementation "androidx.appcompat:appcompat:1.3.1"
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
    implementation "com.google.android.material:material:1.12.0"
    implementation "com.github.bumptech.glide:glide:4.12.0"
    implementation "com.google.code.gson:gson:2.9.1"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.+"
    implementation "com.tencent.liteav:LiteAVSDK_Professional:12.8.+"
    implementation "com.tencent.imsdk:imsdk-plus:8.8.+"
    implementation "com.tencent.liteav.tuikit:tuicore:8.7.+"
    implementation "io.trtc.uikit:rtc_room_engine:3.5+"
    implementation "io.trtc.uikit:common:3.5+"
    implementation "com.tencent.liteav.tuikit:tuicallkit:3.5+"
    implementation "androidx.work:work-runtime-ktx:2.8.1"
}
